Outgoing module
riesendaniel/myFinanceTracker pull request #34
Opened 2018-10-04 12:59 UTC by riesendaniel

#5

2018-10-04 17:32 UTC, sarner commented
Es hat noch sehr viele Linting-Fehler, falls du diese bereinigen möchtest.

2018-10-04 17:34 UTC, sarner commented
Für das Menü würde ich eine deutsche Bezeichnung verwenden. z.B. Ausgaben statt Outgoings

2018-10-04 17:41 UTC, sarner commented
Was mir für eine endgültige Version noch fehlt, ist das Bearbeiten und Löschen von Ausgaben.

2018-10-04 17:43 UTC, sarner commented
Würde eine Zusammenfassung mit dem Total der Ausgaben noch Sinn machen?

2018-10-04 17:58 UTC, sarner commented
Wir müssen uns dann irgendwann noch einigen, ob wir das _props_- und _actions_-Binding im Componenten machen oder dafür Container verwenden.

2018-10-04 18:09 UTC, sarner requested changes

2018-10-04 18:09 UTC, sarner commented on src/components/OutgoingListComponent.jsx
> +                            <Button type='button' onClick={() => {
Anstelle des _Button_-Komponenten würde ich den _IconButton_-Komponenten verwenden.

2018-10-04 18:09 UTC, sarner commented on src/components/OutgoingItemComponent.jsx
> +                <TableCell>{this.props.outgoing.outgoingAmount}</TableCell>
Vielleicht könnte man da noch die Währung anzeigen.

2018-10-04 18:09 UTC, sarner commented on src/components/NewOutgoingComponent.jsx
> +                            <InputAdornment position="start">CHF</InputAdornment>
Ich habe die Währung in den _AppReducer_ ausgelagert. Ggf. könntest du auch diese Variable verwenden

2018-10-04 18:09 UTC, sarner commented on src/components/NewOutgoingComponent.jsx
> +                <TextField
Für den Nutzer ist es besser (und weniger fehleranfällig), wenn er aus einer Liste auswählen kann. Wir müssen uns da noch einig werden, wie wir die Kategorien zwischen Budget und Ausgaben handeln.

2018-10-04 18:09 UTC, sarner commented on src/components/OutgoingItemComponent.jsx
> +                <TableCell>{this.props.outgoing.outgoingDate}</TableCell>
Das Datum von neu hinzugefügten Ausgaben wird im falschen Format (_JJJJ-MM-TT_) dargestellt.

2018-10-04 18:09 UTC, sarner commented on src/components/AppComponent.jsx
> +                <Route component={NotFound}/>
Gute Idee, scheint aber leider nicht zu funktionieren.

2018-10-04 18:09 UTC, sarner commented on src/components/NewOutgoingComponent.jsx
> +            id: uuid(),
Entspricht das den Anforderungen der Datenbank?

2018-10-04 18:09 UTC, sarner commented on src/components/NewOutgoingComponent.jsx
> +                {this.state.isOutgoingSaved && <Redirect to='/outgoings' push/>}
Wir müssen uns noch einigen, ob wir das so lösen oder so, wie im Branch _redirect_ ein Beispiel ist.

2018-10-04 18:09 UTC, sarner commented on src/components/NewOutgoingComponent.jsx
> +const uuid = ()=> {
Wenn wir UUIDs verwenden, würde ich diese Funktion in eine Helper-Datei auslagern.

2018-10-08 17:49 UTC, riesendaniel commented
@sarner kannst du den pullrequest nochmals anschauen? 
#42 <- diese Änderungen werden später noch gemacht

2018-10-10 18:03 UTC, sarner approved these changes

2018-10-10 18:03 UTC, merged