Finetuning modul outgoing
riesendaniel/myFinanceTracker pull request #55
Opened 2018-10-30 06:42 UTC by riesendaniel

2018-10-31 17:43 UTC, sarner requested changes
Aus meiner Sicht fehlt zur Erfüllung des Issues noch ein Filter für die Spalten. Evt. sollten wir dafür die Komponente [MUI-Datatables](https://github.com/gregnb/mui-datatables) verwenden, welche auf eine gewisse Art und Weise auch responsive Design unterstützen würde...

Bei meinem Test haben zudem die Aktionen _Bearbeiten_ und _Löschen_ nicht funktioniert. Vielleicht liegt das auch nur daran, dass die neu erfassten Ausgaben keine richtige ID hatten?

2018-10-31 17:43 UTC, sarner commented on src/components/OutgoingListComponent.jsx
> +import TablePagination from '@material-ui/core/TablePagination';
Das könntest du in Zeile 3 ergänzen.

2018-10-31 17:43 UTC, sarner commented on src/components/OutgoingListComponent.jsx
> +import TextField from '@material-ui/core/TextField/TextField';
Das könntest du in Zeile 3 ergänzen.

2018-10-31 17:43 UTC, sarner commented on src/components/OutgoingListComponent.jsx
> +                numSelected={this.state.selected.length}
Kann gelöscht werden, da es nicht verwendet wird.
```suggestion

```

2018-10-31 17:43 UTC, sarner commented on src/components/OutgoingListComponent.jsx
> +            <TextField placeholder=".. suche .." onChange={this.handleSearch}
Ich würde den _Placeholder_ sprechender gestalten (z.B. "Nach einer Bezeichnung suchen...").

2018-10-31 17:43 UTC, sarner commented on src/components/OutgoingListComponent.jsx
> +                rowCount={outgoings.length}
Kann gelöscht werden, da es nicht verwendet wird.
```suggestion

```

2018-10-31 17:43 UTC, sarner commented on src/components/OutgoingListComponent.jsx
> +        .format('DD.MM.YYYY').includes(this.state.searchValue.toLowerCase()));
Aus meiner Sicht genügt die Suche nach Bezeichnung. Alles andere kann über Filter gelöst werden.

2018-10-31 17:43 UTC, sarner commented on src/components/OutgoingTableHead.jsx
> +import Tooltip from '@material-ui/core/Tooltip';
Das könntest du in Zeile 2 ergänzen.

2018-10-31 17:43 UTC, sarner commented on src/components/OutgoingTableHead.jsx
> +                {!row.disableSort > 0 &&
Wäre hier `row.enableSort` nicht verständlicher?
Warum vergleichst du mit 0?

2018-10-31 17:43 UTC, sarner commented on src/components/OutgoingTableHead.jsx
> +                  title="Sort"
Ich würde eine deutsche Bezeichnung verwenden.

2018-10-31 17:43 UTC, sarner commented on src/components/OutgoingListComponent.jsx
> +            />
Ich würde noch die Eigenschaft `labelRowsPerPage` verwenden, um eine deutsche Bezeichnung darzustellen.

2018-10-31 17:43 UTC, sarner commented on src/components/OutgoingListComponent.jsx
> +                      row.outgoingCategory = category[0].description;
Das scheint irgendwie nicht zu funktionieren. Es wird nur die Zahl dargestellt.

2018-10-31 17:43 UTC, sarner commented on src/components/OutgoingListComponent.jsx
> +              count={outgoings.length}
Müsste der _count_ sich nicht auf die dargestellten Einträge statt alle Einträge beziehen?

2018-10-31 17:43 UTC, sarner commented on src/components/OutgoingTableHead.jsx
> +  numSelected: PropTypes.number.isRequired,
Kann gelöscht werden, da es nie verwendet wird.

2018-10-31 17:43 UTC, sarner commented on src/components/OutgoingTableHead.jsx
> +  rowCount: PropTypes.number.isRequired,
Kann gelöscht werden, da es nie verwendet wird.

2018-11-01 07:11 UTC, riesendaniel commented
Den Filter gibt es ja indirekt mit der Suche, also dort wird ja gefiltert.. Für was ist der Filter noch hilfreich oder unterscheidet sich dieser zur Suche?

2018-11-01 07:15 UTC, riesendaniel commented on src/components/OutgoingListComponent.jsx
> +import TablePagination from '@material-ui/core/TablePagination';
Das ist mir nicht ganz klar, was meinst du genau?

2018-11-01 07:15 UTC, riesendaniel commented on src/components/OutgoingListComponent.jsx
> +import TextField from '@material-ui/core/TextField/TextField';
Das ist mir nicht ganz klar, was meinst du genau?

2018-11-01 07:34 UTC, riesendaniel commented on src/components/OutgoingListComponent.jsx
> +            />
Guter Hinweis

2018-11-01 07:39 UTC, riesendaniel commented
habe den rest gefixt, offen sind noch die ersten beiden kommentare (Das könntest du in Zeile 3 ergänzen.) und das mit dem filter.

2018-11-01 07:45 UTC, riesendaniel commented
ah genau das löschen und bearbeiten habe ich nur in die console geloggt, weil ich das ja dann mit firebase umgesetzt habe, daher habe ich es nicht mehr implementiert in diesem Branch :)

2018-11-01 17:41 UTC, sarner commented on src/components/OutgoingListComponent.jsx
> +import TablePagination from '@material-ui/core/TablePagination';
Du könntest `import { IconButton, Paper, Table, TableBody, } from '@material-ui/core';` ergänzen zu `import { IconButton, Paper, Table, TableBody, TablePagination } from '@material-ui/core';`. Das würde dann auch noch funktionieren, oder?

2018-11-01 17:43 UTC, sarner commented on src/components/OutgoingListComponent.jsx
> +import TextField from '@material-ui/core/TextField/TextField';
Auch hier könntest du wahrscheinlich `import { IconButton, Paper, Table, TableBody, } from '@material-ui/core';` zu `import { IconButton, Paper, Table, TableBody, TextField } from '@material-ui/core';` machen.

2018-11-01 17:45 UTC, sarner commented
> Den Filter gibt es ja indirekt mit der Suche, also dort wird ja gefiltert.. Für was ist der Filter noch hilfreich oder unterscheidet sich dieser zur Suche?

Die Suche beinhaltet weder Kategorie noch Datum. Beim Datum wäre ein Filter zum Beispiel nützlich um >, < oder zwischen zu verwenden. Selbes gilt für den Betrag.

2018-11-02 06:42 UTC, riesendaniel commented on src/components/OutgoingListComponent.jsx
> +                      row.outgoingCategory = category[0].description;
Das habe ich auch im Firebase branch behoben. Mache es hier nicht, sonst habe ich noch merge probleme anschliessend ;)

2018-11-02 07:16 UTC, riesendaniel commented on src/components/OutgoingListComponent.jsx
> +import TablePagination from '@material-ui/core/TablePagination';
done

2018-11-02 07:16 UTC, riesendaniel commented on src/components/OutgoingListComponent.jsx
> +import TextField from '@material-ui/core/TextField/TextField';
done

2018-11-02 07:16 UTC, riesendaniel commented on src/components/OutgoingListComponent.jsx
> +                numSelected={this.state.selected.length}
done

2018-11-02 07:16 UTC, riesendaniel commented on src/components/OutgoingListComponent.jsx
> +            <TextField placeholder=".. suche .." onChange={this.handleSearch}
done

2018-11-02 07:16 UTC, riesendaniel commented on src/components/OutgoingListComponent.jsx
> +                rowCount={outgoings.length}
done

2018-11-02 07:16 UTC, riesendaniel commented on src/components/OutgoingListComponent.jsx
> +              count={outgoings.length}
done

2018-11-02 07:16 UTC, riesendaniel commented on src/components/OutgoingTableHead.jsx
> +  numSelected: PropTypes.number.isRequired,
done

2018-11-02 07:16 UTC, riesendaniel commented on src/components/OutgoingTableHead.jsx
> +  rowCount: PropTypes.number.isRequired,
done

2018-11-02 07:19 UTC, riesendaniel commented
Ich habe nun einen Filter auf die Kategorie eingebaut. Ich glaube das braucht man am meisten. Man will eine Kategorie filtern und schauen wie viel man ausgegeben hat.
Oder meinst du dass es Sinn macht noch den Betrag mit grösser und kleiner gleich zu filtern?

2018-11-03 09:39 UTC, sarner approved these changes

2018-11-03 09:40 UTC, merged