Firebase database auth
riesendaniel/myFinanceTracker pull request #60
Opened 2018-11-10 22:25 UTC by riesendaniel

database & auth

2018-11-10 22:25 UTC, riesendaniel commented
ich lösche den anderen pullrequest, habe nun beides in einem integriert.

2018-11-12 18:48 UTC, sarner requested changes
Die Bedienung und Speicherung hat bei mir leider nicht so ganz funktioniert. Ansonsten muss ich es mir später nochmals anschauen...

Vielleicht kannst du gleich auch noch die Konflikte lösen.

2018-11-12 21:15 UTC, riesendaniel commented
stimmt bei budget springt er irgendwie nicht zurück, das ist mir irgendwie nicht klar. bei den ausgaben funktioniert alles wunderbar.. das muss ich mir noch anschauen, komme aber erst morgen dazu

2018-11-14 15:34 UTC, sarner approved these changes

2018-11-14 15:34 UTC, merged